### ISSUE TITLE
svnsync: E170001: Authorization failed

### ISSUE THREAD

**Issue by EraseLiu** [garethflowers/docker-svn-server#6]
No permission when initializing the image library operation.

- The user `syncuser` has read and write permissions in `svn-source` and `svn-mirror`
- The mounted directory is given permission using `chmod 777 -R svn-mirror`
- Without the docker service (svn://), use `file:///usr/local/docker/svn-server/svn/svn-mirror` to successfully initialize.

Here are some of my configuration.
Thank you.

`/usr/local/docker/svn-server/svn/svn-mirror/hooks/pre-revprop-change`
```sh
#!/bin/sh
exit 0
```
`docker-compose.yml`
```ymll
version: '2'
services:
  svn-server:
    image: garethflowers/svn-server:1.3.3
    volumes:
    - /usr/local/docker/svn-server/svn:/var/opt/svn
    ports:
    - 3690:3690/tcp
    restart: always
```
initialize
```base
$ svnsync initialize \
    svn://192.168.1.10:3690/svn-mirror \
    svn://192.168.1.11:3690/svn-source\
    --username syncuser --password syncpasswd
svnsync: E170001: Authorization failed
```
